### PR TITLE
fix focus

### LINKED ISSUE #8630: mention .focus() doesn't work
### Version
3.0.1

### Environment
browser

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
when componentDidMount()  invoke this.mention.focus()

### What is expected?
when invoke this.mention.focus(), it is should work
u website, the api demo does not working and codepen does not working either.
so ... fix it 

### What is actually happening?
not working,
editor does not focus

### PR DESCRIPTION
**Pull request by RaoHai**
+ close https://github.com/ant-design/ant-design/issues/8630

### CODE REVIEW

File: src/EditorCore/index.tsx [hunk 1]
```diff
@@ -330,18 +331,22 @@ class EditorCore extends React.Component<EditorProps, EditorCoreState> {
...
       && document.activeElement.getAttribute('contenteditable') === 'true'
     ) {
       return;
     }
 
+    return this.focus(ev);
+  }
+
+  public focus(ev) : void {
+    const event = ev && ev.nativeEvent;
```
Comment (yutingzhao1991) [inline src/EditorCore/index.tsx:349]: ev probably is undefined.

**Comment by afc163** [comment]
@RaoHai 来看下，两个问题。

- [ ] http://ant.design/components/mention-cn/ 挂了，上面的 event 是 undefined。
- [ ] 修复了 event 之后，focus 方法执行完，光标没有 focus 到输入框内。

**Comment by RaoHai** [comment]
* [ ] https://github.com/react-component/editor-core/pull/15
* [ ] https://github.com/ant-design/ant-design/pull/9548
